name: Full Test Suite

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install dependencies
      run: yarn
    - name: Format code
      run: yarn run format:ci
    - name: Git Diff TS/JS
      run: yarn run gitdiff:ci
    - name: Lint Code
      run: yarn run lint
    - name: Lint test
      run: yarn run lint:tests
    - name: Coverage
      run: yarn run coverage
